namespace Astra.Core.Localization;

internal static class TurkishStrings
{
    public static readonly Dictionary<string, string> Map = new()
    {
        // Navigation & window
        ["Search settings"] = "Ayarlarda ara",
        ["Home"] = "Ana sayfa",
        ["Settings"] = "Ayarlar",
        ["General"] = "Genel",
        ["AI model"] = "Yapay zekâ modeli",
        ["Voice"] = "Ses",
        ["Appearance"] = "Görünüm",
        ["Automation"] = "Otomasyon",
        ["Security"] = "Güvenlik",
        ["Computer index"] = "Bilgisayar dizini",
        ["Memory"] = "Bellek",

        // Search entries
        ["Assistant name"] = "Asistan adı",
        ["Start with Windows"] = "Windows ile başlat",
        ["Minimize to tray"] = "Sistem tepsisine küçült",
        ["Language"] = "Dil",
        ["Reset all settings"] = "Tüm ayarları sıfırla",
        ["AI provider"] = "Yapay zekâ sağlayıcısı",
        ["API key"] = "API anahtarı",
        ["Model"] = "Model",
        ["Test connection"] = "Bağlantıyı test et",
        ["Ollama"] = "Ollama",
        ["Microphone"] = "Mikrofon",
        ["Wake word"] = "Uyandırma kelimesi",
        ["Push-to-talk"] = "Bas-konuş",
        ["Text-to-speech voice"] = "Metin okuma sesi",
        ["Response language"] = "Yanıt dili",
        ["Theme"] = "Tema",
        ["Accent color"] = "Vurgu rengi",
        ["Astra icon"] = "Astra simgesi",
        ["HUD"] = "HUD",
        ["AI cursor"] = "Yapay zekâ imleci",
        ["Audio visualizer"] = "Ses görselleştirici",
        ["Animations"] = "Animasyonlar",
        ["Notifications"] = "Bildirimler",
        ["Browser"] = "Tarayıcı",
        ["UI Automation"] = "UI Otomasyonu",
        ["Mouse and keyboard"] = "Fare ve klavye",
        ["Verify actions"] = "İşlemleri doğrula",
        ["Local-first intents"] = "Önce yerel çözümleme",
        ["Permissions"] = "İzinler",
        ["Confirm destructive actions"] = "Yıkıcı işlemleri onayla",
        ["Stored credentials"] = "Kayıtlı kimlik bilgileri",
        ["Scan Windows"] = "Windows'u tara",
        ["Excluded folders"] = "Hariç tutulan klasörler",
        ["Watch for changes"] = "Değişiklikleri izle",
        ["Short-term context"] = "Kısa süreli bağlam",

        // Home
        ["Welcome to Astra"] = "Astra'ya hoş geldin",
        ["Your natural-language interface to Windows. Finish setup below; each item opens the matching settings page."] =
            "Windows'a doğal dille erişim arayüzün. Aşağıdaki kurulumu tamamla; her öğe ilgili ayar sayfasını açar.",
        ["Setup"] = "Kurulum",
        ["Configure"] = "Yapılandır",
        ["Review"] = "Gözden geçir",
        ["Privacy by design"] = "Tasarımdan gelen gizlilik",
        ["Astra keeps a local index of your computer and gives the AI model only the minimal result of each scoped search. Your file list is never sent in bulk."] =
            "Astra bilgisayarının yerel bir dizinini tutar ve yapay zekâ modeline yalnızca her kapsamlı aramanın asgari sonucunu verir. Dosya listen asla toplu olarak gönderilmez.",
        ["{0} · {1}"] = "{0} · {1}",
        ["{0} · choose a model"] = "{0} · bir model seç",
        ["{0} · API key required"] = "{0} · API anahtarı gerekli",
        ["Wake word “{0}” · listening for the wake word"] = "Uyandırma kelimesi “{0}” · kelimeyi dinliyor",
        ["Wake word “{0}” · push-to-talk"] = "Uyandırma kelimesi “{0}” · bas-konuş",
        ["Index ready"] = "Dizin hazır",
        ["Not scanned yet. Astra can’t find apps and files locally until it is."] =
            "Henüz taranmadı. Taranana kadar Astra uygulamaları ve dosyaları yerel olarak bulamaz.",
        ["{0} of {1} categories ask before acting"] = "{1} kategoriden {0} tanesi işlemden önce soruyor",

        // General
        ["Identity, startup behavior and app data."] = "Kimlik, başlangıç davranışı ve uygulama verileri.",
        ["Assistant"] = "Asistan",
        ["How Astra refers to itself in replies and in the window."] = "Astra'nın yanıtlarda ve pencerede kendinden nasıl söz edeceği.",
        ["Interface language"] = "Arayüz dili",
        ["Language of menus and settings. Voice replies are configured under Voice."] =
            "Menülerin ve ayarların dili. Sesli yanıtlar Ses bölümünden ayarlanır.",
        ["Match Windows"] = "Windows ile aynı",
        ["Startup"] = "Başlangıç",
        ["Launch Astra in the background when you sign in."] = "Oturum açtığında Astra'yı arka planda başlat.",
        ["Start minimized"] = "Küçültülmüş başlat",
        ["Don’t show the window on launch."] = "Açılışta pencereyi gösterme.",
        ["Closing the window keeps Astra running in the notification area."] =
            "Pencereyi kapatmak Astra'yı bildirim alanında çalışır durumda tutar.",
        ["Data"] = "Veri",
        ["App data folder"] = "Uygulama veri klasörü",
        ["Open folder"] = "Klasörü aç",
        ["Restore every option to its default. Saved API keys are kept."] =
            "Tüm seçenekleri varsayılana döndür. Kayıtlı API anahtarları korunur.",
        ["Reset…"] = "Sıfırla…",
        ["About"] = "Hakkında",
        ["Astra"] = "Astra",
        ["AI desktop agent for Windows · version {0} · .NET {1} · WinUI 3"] = "Windows için yapay zekâ masaüstü ajanı · sürüm {0} · .NET {1} · WinUI 3",
        ["Reset all settings?"] = "Tüm ayarlar sıfırlansın mı?",
        ["Every option returns to its default value. Your saved API keys are not removed."] =
            "Tüm seçenekler varsayılan değerine döner. Kayıtlı API anahtarların silinmez.",
        ["Reset"] = "Sıfırla",
        ["Cancel"] = "İptal",

        // AI
        ["Pick the model Astra uses for reasoning and planning. Simple commands are handled locally without calling it."] =
            "Astra'nın akıl yürütme ve planlama için kullandığı modeli seç. Basit komutlar modeli çağırmadan yerelde işlenir.",
        ["Provider"] = "Sağlayıcı",
        ["Cloud providers use their API; Ollama runs models on this PC."] = "Bulut sağlayıcıları kendi API'lerini kullanır; Ollama modelleri bu bilgisayarda çalıştırır.",
        ["Endpoint"] = "Uç nokta",
        ["Base URL of the server."] = "Sunucunun temel URL'si.",
        ["Stored in Windows Credential Manager. Never written to the settings file."] =
            "Windows Kimlik Bilgisi Yöneticisi'nde saklanır. Ayar dosyasına asla yazılmaz.",
        ["Save"] = "Kaydet",
        ["Remove"] = "Kaldır",
        ["Chat model"] = "Sohbet modeli",
        ["Select or type a model"] = "Bir model seç veya yaz",
        ["Pick from the list or type any model name your provider supports."] =
            "Listeden seç veya sağlayıcının desteklediği herhangi bir model adını yaz.",
        ["Contacts the provider and loads the models available to your account."] =
            "Sağlayıcıya bağlanır ve hesabında bulunan modelleri yükler.",
        ["Vision"] = "Görüntü",
        ["Vision provider"] = "Görüntü sağlayıcısı",
        ["Used for screen analysis such as “click the red button”."] = "“Kırmızı butona tıkla” gibi ekran analizi için kullanılır.",
        ["Same as chat model"] = "Sohbet modeliyle aynı",
        ["What the model sees"] = "Modelin gördükleri",
        ["Only your request and the minimal result of each scoped tool call are sent. Your app list, file tree and system details stay on this PC."] =
            "Yalnızca isteğin ve her kapsamlı araç çağrısının asgari sonucu gönderilir. Uygulama listen, dosya ağacın ve sistem ayrıntıların bu bilgisayarda kalır.",
        ["Paste your API key"] = "API anahtarını yapıştır",
        ["Key saved — paste a new one to replace"] = "Anahtar kaydedildi — değiştirmek için yenisini yapıştır",
        ["API key saved to Windows Credential Manager."] = "API anahtarı Windows Kimlik Bilgisi Yöneticisi'ne kaydedildi.",
        ["Could not store the key: {0}"] = "Anahtar saklanamadı: {0}",
        ["API key removed."] = "API anahtarı kaldırıldı.",
        ["Success"] = "Başarılı",
        ["Connection problem"] = "Bağlantı sorunu",
        ["Info"] = "Bilgi",
        ["API key is missing."] = "API anahtarı eksik.",
        ["Authentication failed. Check your API key."] = "Kimlik doğrulama başarısız. API anahtarını kontrol et.",
        ["Endpoint not found. Check the base URL."] = "Uç nokta bulunamadı. Temel URL'yi kontrol et.",
        ["Rate limited by the provider."] = "Sağlayıcı istek sınırına ulaşıldı.",
        ["Server returned {0} {1}."] = "Sunucu {0} {1} döndürdü.",
        ["Connected. {0} models available."] = "Bağlandı. {0} model mevcut.",
        ["Connected."] = "Bağlandı.",
        ["Connection timed out."] = "Bağlantı zaman aşımına uğradı.",
        ["Could not reach the server: {0}"] = "Sunucuya ulaşılamadı: {0}",
        ["Unexpected response from the server."] = "Sunucudan beklenmeyen yanıt.",
        ["Ollama (local)"] = "Ollama (yerel)",
        ["OpenAI-compatible API"] = "OpenAI uyumlu API",

        // Voice
        ["How Astra hears you and how it talks back."] = "Astra seni nasıl duyar ve nasıl yanıt verir.",
        ["Listening"] = "Dinleme",
        ["Input device used for wake word and speech recognition."] = "Uyandırma kelimesi ve konuşma tanıma için kullanılan giriş aygıtı.",
        ["System default"] = "Sistem varsayılanı",
        ["Activation"] = "Etkinleştirme",
        ["Wake word listens continuously for its name; push-to-talk only listens while you hold the hotkey."] =
            "Uyandırma kelimesi sürekli adını dinler; bas-konuş yalnızca kısayol tuşunu basılı tuttuğun sürece dinler.",
        ["Astra only activates after hearing this word."] = "Astra yalnızca bu kelimeyi duyduktan sonra devreye girer.",
        ["Push-to-talk hotkey"] = "Bas-konuş kısayolu",
        ["Hold to speak, release to send."] = "Konuşmak için basılı tut, göndermek için bırak.",
        ["Speech recognition"] = "Konuşma tanıma",
        ["More engines (local Whisper) will appear here in a later release."] = "Daha fazla motor (yerel Whisper) sonraki sürümlerde burada görünecek.",
        ["Windows speech recognition"] = "Windows konuşma tanıma",
        ["Speaking"] = "Konuşma",
        ["Speak responses"] = "Yanıtları sesli oku",
        ["Read replies aloud."] = "Yanıtları yüksek sesle oku.",
        ["Voice provider"] = "Ses sağlayıcısı",
        ["External and local neural TTS engines will appear here later."] = "Harici ve yerel nöral TTS motorları daha sonra burada görünecek.",
        ["Windows voices"] = "Windows sesleri",
        ["Installed Windows voices. Add more under Windows Settings ▸ Time & language ▸ Speech."] =
            "Yüklü Windows sesleri. Daha fazlasını Windows Ayarları ▸ Saat ve dil ▸ Konuşma bölümünden ekleyebilirsin.",
        ["Speed"] = "Hız",
        ["Volume"] = "Ses düzeyi",
        ["Reply language"] = "Yanıt dili",
        ["Auto answers in the language you spoke."] = "Otomatik, konuştuğun dilde yanıt verir.",
        ["Detect automatically"] = "Otomatik algıla",
        ["Test voice"] = "Sesi dene",
        ["Plays a short sample with the settings above."] = "Yukarıdaki ayarlarla kısa bir örnek çalar.",
        ["Play sample"] = "Örneği çal",
        ["Wake word"] = "Uyandırma kelimesi",

        // Appearance
        ["Themes, icon and the on-screen presence of Astra. Every element works independently."] =
            "Temalar, simge ve Astra'nın ekrandaki görünümü. Her öğe bağımsız çalışır.",
        ["Opening Avast Secure Browser…"] = "Avast Secure Browser açılıyor…",
        ["App color mode"] = "Uygulama renk modu",
        ["Light, dark or follow Windows."] = "Açık, koyu veya Windows'u izle.",
        ["Light"] = "Açık",
        ["Dark"] = "Koyu",
        ["Used for toggles, buttons and Astra’s overlays."] = "Anahtarlarda, düğmelerde ve Astra'nın katmanlarında kullanılır.",
        ["Icon"] = "Simge",
        ["Custom icon"] = "Özel simge",
        ["Use your own PNG or SVG. It replaces the built-in icon in the app, HUD, cursor and tray."] =
            "Kendi PNG veya SVG dosyanı kullan. Uygulamadaki, HUD'daki, imleçteki ve tepsideki yerleşik simgenin yerini alır.",
        ["Choose file…"] = "Dosya seç…",
        ["Clear"] = "Temizle",
        ["Overlays"] = "Katmanlar",
        ["Shows listening, thinking and each step Astra is executing."] = "Dinleme, düşünme ve Astra'nın yürüttüğü her adımı gösterir.",
        ["HUD position"] = "HUD konumu",
        ["HUD opacity"] = "HUD opaklığı",
        ["A visual cursor that shows where Astra is acting: idle, listening, thinking, executing, speaking, error."] =
            "Astra'nın nerede işlem yaptığını gösteren görsel imleç: boşta, dinliyor, düşünüyor, yürütüyor, konuşuyor, hata.",
        ["Cursor size"] = "İmleç boyutu",
        ["Reacts to Astra’s voice in real time."] = "Astra'nın sesine gerçek zamanlı tepki verir.",
        ["Visualizer style"] = "Görselleştirici stili",
        ["Visualizer position"] = "Görselleştirici konumu",
        ["Visualizer size"] = "Görselleştirici boyutu",
        ["Visualizer opacity"] = "Görselleştirici opaklığı",
        ["Behavior"] = "Davranış",
        ["Turn off for a static interface and lower CPU use."] = "Sabit bir arayüz ve daha düşük CPU kullanımı için kapat.",
        ["Windows notifications when a task completes or needs you."] = "Bir görev tamamlandığında veya sana ihtiyaç duyduğunda Windows bildirimleri.",
        ["Minimal"] = "Minimal", ["Glass"] = "Cam", ["Cyber"] = "Siber", ["Neon"] = "Neon",
        ["Classic"] = "Klasik", ["Terminal"] = "Terminal", ["Custom"] = "Özel",
        ["Orb"] = "Küre", ["Star"] = "Yıldız", ["Ring"] = "Halka", ["Abstract AI"] = "Soyut YZ",
        ["Spectrum bars"] = "Spektrum çubukları", ["Circular spectrum"] = "Dairesel spektrum", ["Waveform"] = "Dalga biçimi",
        ["Pulse"] = "Nabız", ["None"] = "Yok",
        ["Top left"] = "Sol üst", ["Top right"] = "Sağ üst", ["Bottom left"] = "Sol alt", ["Bottom right"] = "Sağ alt", ["Center"] = "Orta",

        // Automation
        ["How Astra controls apps, the browser, mouse and keyboard."] = "Astra uygulamaları, tarayıcıyı, fareyi ve klavyeyi nasıl kontrol eder.",
        ["Preferred browser"] = "Tercih edilen tarayıcı",
        ["Used when you don’t name a browser. Detected from Windows."] = "Bir tarayıcı belirtmediğinde kullanılır. Windows'tan algılanır.",
        ["No browsers detected. Astra will use the Windows default."] = "Tarayıcı algılanmadı. Astra Windows varsayılanını kullanacak.",
        ["{0} browser(s) detected. Used when you don’t name one."] = "{0} tarayıcı algılandı. Birini belirtmediğinde kullanılır.",
        ["Control"] = "Kontrol",
        ["Prefer UI Automation"] = "UI Otomasyonunu tercih et",
        ["Target buttons and fields through Windows accessibility info instead of screen coordinates. More reliable."] =
            "Düğmeleri ve alanları ekran koordinatları yerine Windows erişilebilirlik bilgisiyle hedefle. Daha güvenilir.",
        ["Allow mouse control"] = "Fare kontrolüne izin ver",
        ["Allow keyboard control"] = "Klavye kontrolüne izin ver",
        ["Verify every action"] = "Her işlemi doğrula",
        ["Check the result after each step and try another method if it failed."] = "Her adımdan sonra sonucu kontrol et ve başarısız olursa başka bir yöntem dene.",
        ["Delay between actions"] = "İşlemler arası gecikme",
        ["Increase for slower PCs or apps that load gradually."] = "Yavaş bilgisayarlar veya kademeli yüklenen uygulamalar için artır.",
        ["Agent"] = "Ajan",
        ["Resolve simple commands like “open Chrome” on this PC without calling the AI model. Saves tokens and time."] =
            "“Chrome'u aç” gibi basit komutları yapay zekâ modelini çağırmadan bu bilgisayarda çöz. Token ve zaman tasarrufu sağlar.",
        ["Maximum steps per task"] = "Görev başına en fazla adım",
        ["Astra stops and asks you if a task needs more steps than this."] = "Bir görev bundan fazla adım gerektirirse Astra durur ve sana sorar.",
        ["{0} ms"] = "{0} ms",

        // Security
        ["Decide what Astra may do on its own and what needs your approval."] = "Astra'nın kendi başına neler yapabileceğine ve neyin onayına ihtiyaç duyduğuna karar ver.",
        ["Applications"] = "Uygulamalar",
        ["Open, close and list running programs."] = "Çalışan programları aç, kapat ve listele.",
        ["Files"] = "Dosyalar",
        ["Navigate, search and interact with web pages."] = "Web sayfalarında gezin, ara ve etkileşime gir.",
        ["Create, move, copy and delete files and folders."] = "Dosya ve klasörleri oluştur, taşı, kopyala ve sil.",
        ["Mouse & keyboard"] = "Fare ve klavye",
        ["Click, type and press keys on your behalf."] = "Senin adına tıkla, yaz ve tuşlara bas.",
        ["Run shell commands."] = "Kabuk komutları çalıştır.",
        ["System settings"] = "Sistem ayarları",
        ["Change Windows settings."] = "Windows ayarlarını değiştir.",
        ["Shutdown / restart"] = "Kapat / yeniden başlat",
        ["Turn off, restart, sleep or sign out."] = "Kapat, yeniden başlat, uyku moduna al veya oturumu kapat.",
        ["Ask every time"] = "Her seferinde sor",
        ["Always allow"] = "Her zaman izin ver",
        ["Never allow"] = "Asla izin verme",
        ["Confirmation rules"] = "Onay kuralları",
        ["Always confirm destructive actions"] = "Yıkıcı işlemleri her zaman onayla",
        ["Deleting, overwriting or other irreversible actions always ask first, whatever the category setting."] =
            "Silme, üzerine yazma veya geri alınamayan diğer işlemler, kategori ayarı ne olursa olsun önce sorar.",
        ["Confirm deleting this many files or more"] = "Bu kadar veya daha fazla dosya silinirken onayla",
        ["Bulk operations at or above this count show the exact number before running."] =
            "Bu sayıya ulaşan veya aşan toplu işlemler çalışmadan önce kesin sayıyı gösterir.",
        ["Stored credentials"] = "Kayıtlı kimlik bilgileri",
        ["Remove {0} key?"] = "{0} anahtarı kaldırılsın mı?",
        ["The key is deleted from Windows Credential Manager. You can add it again later."] =
            "Anahtar Windows Kimlik Bilgisi Yöneticisi'nden silinir. Daha sonra tekrar ekleyebilirsin.",
        ["API key saved in Windows Credential Manager"] = "API anahtarı Windows Kimlik Bilgisi Yöneticisi'nde kayıtlı",
        ["No API keys stored."] = "Kayıtlı API anahtarı yok.",

        // Index
        ["A local search index of your apps and files, so Astra finds things instantly without sending your computer to an AI model."] =
            "Uygulamalarının ve dosyalarının yerel arama dizini; böylece Astra bilgisayarını bir yapay zekâ modeline göndermeden her şeyi anında bulur.",
        ["Status"] = "Durum",
        ["Index status"] = "Dizin durumu",
        ["The scanner is added in the next development phase."] = "Tarayıcı bir sonraki geliştirme aşamasında eklenecek.",
        ["Index ready."] = "Dizin hazır.",
        ["Not built yet. The Windows scanner arrives in the next development phase; your options below are saved for it."] =
            "Henüz oluşturulmadı. Windows tarayıcısı bir sonraki geliştirme aşamasında gelecek; aşağıdaki seçeneklerin onun için kaydedilir.",
        ["Options"] = "Seçenekler",
        ["Keep the index up to date"] = "Dizini güncel tut",
        ["Watch for new, renamed and deleted files and for installed or removed apps. No full rescans."] =
            "Yeni, yeniden adlandırılan ve silinen dosyaları, yüklenen veya kaldırılan uygulamaları izle. Tam yeniden tarama yok.",
        ["Index file metadata"] = "Dosya meta verilerini dizinle",
        ["Names, types, sizes and dates only. File contents are never read unless a task needs them."] =
            "Yalnızca adlar, türler, boyutlar ve tarihler. Bir görev gerektirmedikçe dosya içerikleri asla okunmaz.",
        ["Folders Astra never indexes"] = "Astra'nın asla dizinlemediği klasörler",
        ["Anything inside these folders is invisible to search."] = "Bu klasörlerin içindeki her şey aramada görünmez.",
        ["Add folder…"] = "Klasör ekle…",

        // Memory
        ["What Astra remembers between requests and between sessions."] = "Astra'nın istekler ve oturumlar arasında hatırladıkları.",
        ["Conversation"] = "Konuşma",
        ["Remember context"] = "Bağlamı hatırla",
        ["Let Astra remember preferences you tell it. Turn off to start fresh every time."] =
            "Astra'nın söylediğin tercihleri hatırlamasına izin ver. Her seferinde sıfırdan başlamak için kapat.",
        ["How many recent exchanges are sent along with a new request. Fewer means fewer tokens."] =
            "Yeni bir istekle birlikte kaç son konuşma gönderilir. Daha az, daha az token demektir.",
        ["{0:0} turns"] = "{0:0} tur",
        ["Saved memories"] = "Kayıtlı anılar",
        ["Nothing saved yet"] = "Henüz kayıtlı bir şey yok",
        ["Long-term memories will appear here once the memory system ships, where you can review and delete each one. Astra won’t store passwords or other sensitive details."] =
            "Uzun süreli anılar bellek sistemi geldiğinde burada görünecek; her birini inceleyip silebileceksin. Astra parolaları veya diğer hassas ayrıntıları saklamaz.",
    };
}
